version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=m11
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./core/:/var/www/core:cached']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./core/:/var/www/core:cached']
  redis:
      image: redis:6.2.1-alpine
      ports: ['6379:6379']
      command: ["redis-server", "--appendonly", "yes"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80