doctrine:
    orm:
        metadata_cache_driver: 
            type: pool
            pool: doctrine.cache.metadata
        result_cache_driver: 
            type: pool
            pool: doctrine.cache.result
        query_cache_driver: 
            type: pool
            pool: doctrine.cache.query
